### ISSUE TITLE
delivery setters

### ISSUE THREAD

**Issue by sevcik-poctivaagentura** [mallgroup/mpapi-client-php#1]
Hello,

I'm not sure about the AbstractDelivery class setters. When I want to set min height to 0, min height key will not be created. I think that there should be if statment in setHeightMin method this way:
if ((double) $heightMin !== $this->getHeightMin() **|| !isset($this->data[self::KEY_HEIGHT][self::KEY_MIN])**) 
and also for setLengthMin should be:
if ((double) $lengthMin !== $this->getLengthMin() || !isset($this->data[self::KEY_**LENGTH**][self::KEY_MIN])) 

This way it works for me, but I'm not sure about another dependencies.

Best Regards,
Jan Sevcik

**Comment by janblahamall** [comment]
Hi,
thanks for your report.
We fixed the problem in new release: https://github.com/mallgroup/mpapi-client-php/tree/v1.9.4
