### ISSUE TITLE
Nefunkční atribut adult_only

### ISSUE THREAD

**Issue by soukicz** [mallgroup/mpapi-client-php#13]
Atribut adultOnly nejde změnit. Když se zavolá setAdultOnly, tak to skončí na chybě kvůli neexistujícímu indexu. Do metody se navíc dává bool, ale přitom v getAdultOnly to zase očekává string. V API dokumentaci pak ten atribut zase není vůbec.

**Comment by michalsalon-mall** [comment]
Attribute `adultOnly` has been completely removed from the API in the meantime.
