### ISSUE TITLE
call from localhost ?

### ISSUE THREAD

**Issue by nightstarter** [mallgroup/mpapi-client-php#15]
Hi there, when calling api from my CRM server (not a public server, only local) , I get 

> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Is there a way how to ignore certificate verification ?

Thanks

**Comment by Lumeriol** [comment]
This problem is due you have not valid / defined certificate for cURL on localhost.
You can download actual CA certificate i.e. from https://curl.haxx.se/docs/caextract.html and in php.ini set path in curl.cainfo directive.
After restarting server problem should be resolved.

**Comment by danielrataj** [comment]
Closing due to further inactivity. Please reopen the issue in case of need. Thank you.
