### ISSUE TITLE
Chybí tam "invoices"

### ISSUE THREAD

**Issue by mzvarik** [mallgroup/mpapi-client-php#18]
Optimálně tuhle knihovnu smazat a ať si každý udělá napojení zvlášť:
https://marketplaceapiv2.docs.apiary.io/#introduction/marketplace-v2/api-architecture

Provedení API chválím, jednoduché a srozumitelné.
Stačí file_get_contents(...), žádné Authorization apod.
Tahle PHP knihovna je ale marná, 100 souborů, kvůli pár funkcím 🤦‍♂️

**Comment by michalsalon-mall** [comment]
As of today, version 4 has been officially released with support for Invoices endpoints. If you find any problems, please open a new issue.

Thank you.
