### ISSUE TITLE
Order::getPaymentType má vracet string, ale vrací int

### ISSUE THREAD

**Issue by jancinert** [mallgroup/mpapi-client-php#19]

**Comment by matraux** [comment]
Prosím o změnu:
`	/**
	 * @return int|null
	 */
	public function getPaymentType()
	{
		return InputDataHelper::getNullableInt($this->data, [self::KEY_PAYMENT_TYPE]);
	}
`
na
`
	/**
	 * @return string|null
	 */
	public function getPaymentType()
	{
		return InputDataHelper::getNullableString($this->data, [self::KEY_PAYMENT_TYPE]);
	}
`

**Comment by michalsalon-mall** [comment]
Fixed in [v3.12.2](https://github.com/mallgroup/mpapi-client-php/releases/tag/v3.12.2)
