### ISSUE TITLE
Orders->all() no longer return all orders

### ISSUE THREAD

**Issue by Engazan** [mallgroup/mpapi-client-php#20]
hi,

function **all()** no longer return **all orders**, it always return MAX 9 orders from OLDEST from **2020.20.01 10:00**

it seems like problem is in ```includeTestOrders(true)```

```
$orders = new \MPAPI\Services\Orders($mpapiClient);
$ordersData = $orders->get()->includeTestOrders(true)->all();
```

**Comment by michalsalon-mall** [comment]
Hi,

when i try to call the endpoint directly on our data or using the client, it returns all test orders correctly.
Could you please provide more info (amount of orders returned before etc.)?
I need your partner id (**not** the client id!) to do some debugging. You can send it via PM or **ideally** by contacting your onboarding specialist, where you can provide required details (requests/responses etc.) without exposing them to the public.

Thank you.

**Comment by Engazan** [comment]
We got email from Mall Group about Technical problem in Orders, and they will fix it today

Thanks.

**Comment by michalsalon-mall** [comment]
Yes, there were some problems today, but none of them affected list of test orders AFAIK.
So if it still does not work correctly, let us know.

Thank you.

**Comment by Engazan** [comment]
another update today we found another problem with ```includeTestOrders```, looks like old filters not working at all :(

```php
$allBlockedOrders = $orders->get()->includeTestOrders(true)->blocked();
```

**Comment by michalsalon-mall** [comment]
Hi,

yes we have received a bug ticket about this issue and it is already fixed, but was not deployed to production during weekend.
It should be working correctly now.

Thank you and sorry about the issues.
