### ISSUE TITLE
Nekompatibilní s Symfony 5.2

### ISSUE THREAD

**Issue by soukicz** [mallgroup/mpapi-client-php#21]
Symfony 5.2 má v závislostech psr/log 1.1, ale tento balíček má napevno závislost na psr/log 1.0 - verze jsou kompatibilní, takže je to jen otázka úpravy composer.json

Dokonce tu na to už rok visí pull request: https://github.com/mallgroup/mpapi-client-php/pull/17

**Comment by michalsalon-mall** [comment]
Fixed in [v3.13.0](https://github.com/mallgroup/mpapi-client-php/releases/tag/v3.13.0)

**Comment by soukicz** [comment]
Verze se nepropsala na packagist: https://packagist.org/packages/mallgroup/mpapi-client

**Comment by michalsalon-mall** [comment]
Diky za info, jiz by tam mela byt 🙂
