### ISSUE TITLE
Client v4 Beta testing - feedback and suggestions

### ISSUE THREAD

**Issue by michalsalon-mall** [mallgroup/mpapi-client-php#25]
Hello,

a new **beta** version of the client was released recently: [v4.0.0-beta](https://github.com/mallgroup/mpapi-client-php/tree/client-v4-beta)

We would like to collect any comments and suggestions from you, before the final release.

If you have any questions regarding v4, you may post them here too.

Thank you.

---

### Known issues:
- [x] Incomplete documentation for Products endpoints
- [x] Missing documentation for Orders endpoints
- [ ] Missing support for Transports v2 endpoints

**Comment by koblihcz** [comment]
Proč když aktualizuji dostupnost dle příkladu https://github.com/mallgroup/mpapi-client-php/blob/master/Example/AvailabilityExample.php se neaktualizuje sdostupnost přes endpoint Availability a chybí mi podpora nebo špastně hledám pro dávkovou aktualizaci. Když už MALL tak tlačí na ty limity requestů, bylo by fajn kdyby taky pro to něco udělal.

**Comment by michalsalon-mall** [comment]
Hello @koblihcz,

you are looking at the old v3 client examples. Here are examples for client v4 with batch availability:
https://github.com/mallgroup/mpapi-client-php/blob/client-v4-beta/doc/Article.md#update-availability
https://github.com/mallgroup/mpapi-client-php/blob/client-v4-beta/example/Article.php#L432

In case you have any more questions, do not hesitate to ask.

**Comment by michalsalon-mall** [comment]
As of today, version 4 has been officially released. If you find any problems, please open a new issue.

Thank you.
