### ISSUE TITLE
FILTER_TYPE_BASIC

### ISSUE THREAD

**Issue by gotroch** [mallgroup/mpapi-client-php#3]
$products->setFilter(ProductsEndpoints::FILTER_TYPE_BASIC) cause fatal error Undefined class constant 'FILTER_TYPE_BASIC'.

**Comment by gotroch** [comment]
plz fix your documentation to
$products->setFilter(Products::FILTER_TYPE_BASIC);

**Comment by mdrlikmall** [comment]
Hi Pavel, products doc fixed in v2.10.2, thx.
