### ISSUE TITLE
Missing constant

### ISSUE THREAD

**Issue by Nxis** [mallgroup/mpapi-client-php#4]
Hi,
for some reason, there's missing status `blocked` constant in Order.php:
\MPAPI\Entity\Order\
Order::STATUS_BLOCKED

This status may be returned from unconfirmed orders status endpoint (http://docs.marketplaceapiv2.apiary.io/#reference/orders/get-unconfirmed-orders/get-unconfirmed-order).

**Comment by mdrlikmall** [comment]
STATUS_BLOCKED constant added to the Order entity in client version v2.12.1.
