### ISSUE TITLE
Implementácia

### ISSUE THREAD

**Issue by t0msk** [mallgroup/mpapi-client-php#5]
Dobrý deň,

chcel by som sa spýtať ako môžem implementovať váš PHP klient, snažil som použiť príklad z priečinka Examples, ale dostávam chybu, že script nevie otvoriť vendor/autoload.php, nikde som autoload.php nenašiel, používam webhosting.

**Comment by mdrlikmall** [comment]
Hello, you have to run composer install to generate /vendor/autoload.php, see https://getcomposer.org/. You can run it locally and upload generated files on your webhosting.
